### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by toto6321** [w3nl/ppt-png#1]
Here is my demo.

```
const Converter = require('ppt-png')

new Converter({
    files: ['a.pptx'],
    output: 'output/',
    invert: false,
    logLevel: 2,
    callback: function(data){
        console.log(data.files, data.success, data.files, data.time)
    }
}).run()
```
Then I got:
```
[11:43:06] ~/test_ppt-png $ node index.js 
File: 1, time: 1 ms, total time: 1ms
Average: 1ms/file
Convert: a.pptx
Converted to pdf
Pdf saved: output/a.pdf
Cannot convert: a.pptx
Total time: 517ms for 1 files
[ 'a.pptx' ] [] [ 'a.pptx' ] 517
```
Apparently, it doesn't work as expected. My node is 6.5.0 and OS is Ubuntu 18.

The demo pptx is attached.

[a.pptx](https://github.com/w3nl/ppt-png/files/3288953/a.pptx)

**Comment by w3nl** [comment]
Thanks for your information, I will check it soon.

**Comment by PieterWigboldus** [comment]
Meaby this will help.
pdf2image package failed to convert the pdf to an image.
That package use imagemagick to convert.
https://stackoverflow.com/a/52661288

You can see more usefull debug information if you just show all information from data in the console.

`const Converter = require('ppt-png')

new Converter({
    files: ['a.pptx'],
    output: 'output/',
    invert: false,
    logLevel: 2,
    callback: function(data){
        console.log(data)
    }
}).run()`

**Comment by AlexanderKozhevin** [comment]
```
TypeError: Converter is not a constructor

```

**Comment by pieter-pon** [comment]
Thanks, i'll check

**Comment by w3nl** [comment]
Thanks, i'll check.
On version 1.1.9?

**Comment by AlexanderKozhevin** [comment]
@w3nl @PieterWigboldus  yes 1.1.9

**Comment by w3nl** [comment]
@AlexanderKozhevin I've found this issue, check: https://github.com/w3nl/ppt-png/issues/44#issuecomment-1058202531
