### ISSUE TITLE
Is this package works with vuejs?

### ISSUE THREAD

**Issue by itsdeo** [w3nl/ppt-png#23]
Hi Team,

Is this package works with vuejs?

Thanks in advance

**Comment by w3nl** [comment]
It is a nose.js package, that can convert a file on the server.
You cannot convert it in the browser.
So your vue.js app have to call the server in a request, and than you can convert it on your server.
I hope this answer can help you.

**Comment by itsdeo** [comment]
Okay, Thanks for your prompt response.
Can I implement it on the VueJS project?
Is it Free or it there any limitation on PPT - PNG conversion?

**Comment by w3nl** [comment]
You can use it on your project, it is free to use.
You can use it on Linux, Windows, Mac.
It uses other program's, see the readme.
You need office software than can convert with a command, like LibreOffice or StarOffice, but you can define another. (see the `documentConvert` option)
You also need ImageMagick and pdfinfo

**Comment by itsdeo** [comment]
Thank you!
