### ISSUE TITLE
Setting width and height

### ISSUE THREAD

**Issue by rayit** [w3nl/ppt-png#26]
When setting width and height it's not using it because density is filled in when not provided

**Comment by w3nl** [comment]
Can you create a pull request with the fix?

**Comment by rayit** [comment]
Never done that before will give it a try..

**Comment by w3nl** [comment]
I have publish the version with your fix: https://www.npmjs.com/package/ppt-png/v/0.7.2

**Comment by rayit** [comment]
super, heel erg bedankt!

Dan kan ik mijn fork deleten.

gr

Raymond Marx

On 2020-12-18 14:21, HckrNews wrote:

> I have publish the version with your fix: 
> https://www.npmjs.com/package/ppt-png/v/0.7.2
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] https://github.com/w3nl/ppt-png/issues/26#issuecomment-748080854
[2]
