### ISSUE TITLE
Module not exported

### ISSUE THREAD

**Issue by alexmi256** [w3nl/ppt-png#34]
With `1.1.1` the installed `package.json` has:
```
  "esmodule": "dist/converter.modern.js",
  "exports": {
    ".": {
      "require": "./dist/converter.js",
      "default": "./dist/converter.module.js"
    }
  },
```
But the `dist` directory is empty so you end up getting errors like:
```
Error: Cannot find module '/home/alex/workspace/smweb/automation/node_modules/ppt-png/dist/converter.js'
```

**Comment by w3nl** [comment]
Thanks for reporting, I'll look at this tomorrow.

**Comment by w3nl** [comment]
I have add the files to the package, please check version `1.1.3`.

**Comment by w3nl** [comment]
I have tested the package, and made more changes.
I hope it will work for you.

**Comment by w3nl** [comment]
@alexmi256 Let me know it it works now, so i can close this issue.
