### ISSUE TITLE
No use of this NPM.

### ISSUE THREAD

**Issue by gopal-augment** [w3nl/ppt-png#42]
Really your documentation doesn't work with NodeJs. Waste of time.

**Comment by pieter-pon** [comment]
Sorry, i have to write better documentation indeed. Work in progress.

**Comment by w3nl** [comment]
Sorry, i have to write better documentation indeed. Work in progress.
But it is just created for Node.JS.
Or the documentation or the error's aren't clear enough.

**Comment by gopal-augment** [comment]
I used the same way you mentioned in that link. I got error 

`create is not a function of undefined`

**Comment by w3nl** [comment]
Do you have more information where it happened? (file + line number)
Its now to generic for me.

**Comment by gopal-augment** [comment]
```
const converter = Converter.create({        // **<= this line**
    files:  ['test/OPW 733 Tienduizend redenen.ppt'],
    output: 'output/'
});


const result = converter.convert();
```

**Comment by w3nl** [comment]
How do you import `Converter`?
`import Converter from 'ppt-png'`?

**Comment by gopal-augment** [comment]
I just pasted your code and tried. Changed the file paths.

**Comment by gopal-augment** [comment]
Is this cleared?

**Comment by w3nl** [comment]
I have update the readme with a little more information.
Do you need more information, or can you use the package now?
